"""empty message

Revision ID: 0cdcbf16c7ba
Revises: 1911cc6c9b15
Create Date: 2018-10-07 12:58:31.999486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdcbf16c7ba'
down_revision = '1911cc6c9b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'code')
    # ### end Alembic commands ###
