"""empty message

Revision ID: 441a98ad7761
Revises: 0cdcbf16c7ba
Create Date: 2018-10-07 15:57:29.484297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441a98ad7761'
down_revision = '0cdcbf16c7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
